### ISSUE TITLE
Provide a proper bower.json

### ISSUE THREAD

**Issue by cyrilchaponeverysens** [ValentinH/Leaflet.DomMarkers#1]
A valid _bower.json_ file could be provided, allowing one to install it with that beloved frontend-package-manager.

**Comment by ValentinH** [comment]
Just added it. Can you tell me if it works?

**Comment by cyrilchaponeverysens** [comment]
See b36866d9ca331dbfdf084b8c510534af203425ed

**Comment by cyrilchaponeverysens** [comment]
Tested against _bower_ 1.5.2 and _grunt-wiredep_ 2.0.0.

Everything works fine without any warning.
